# Generated by Django 2.0 on 2017-12-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='started',
            new_name='starter',
        ),
    ]
